name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: go build -o minecraft-panel

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "minecraft-panel,templates,static,start-mcpanel.sh"
          target: "~/minecraft-panel-deploy-temp"

      - name: Deploy and restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # Para a sessão screen antiga, se existir
            screen -S mcpanel -X quit || true

            # Salva o banco locations.db para não perder dados
            mv ~/minecraft-panel/locations.db ~/locations.db.bak || true

            # Remove pasta antiga e substitui pela nova
            rm -rf ~/minecraft-panel
            mv ~/minecraft-panel-deploy-temp ~/minecraft-panel

            # Permissões e script start
            chmod +x ~/minecraft-panel/minecraft-panel
            chmod +x ~/minecraft-panel/start-mcpanel.sh

            # Restaura o banco
            mv ~/locations.db.bak ~/minecraft-panel/locations.db || true

            # Cria o arquivo .env com variáveis secretas
            cat <<EOF > ~/minecraft-panel/.env
            ADMIN_USER=${{ secrets.ADMIN_USER }}
            ADMIN_PASS=${{ secrets.ADMIN_PASS }}
            MINE_PATH=${{ secrets.MINE_PATH }}
            JAVA_COMMAND=${{ secrets.JAVA_COMMAND }}
            EOF

            # Exporta variável BASE_DIR e roda o script de start
            export BASE_DIR=~/minecraft-panel
            bash ~/minecraft-panel/start-mcpanel.sh

            # Aguarda e faz health check
            sleep 3
            curl -f http://localhost:8080/login || (echo "Health check failed" && exit 1)
